name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Ставим зависимости "как получится" (не ломаем пайплайн, если их нет)
      - name: Install deps (best effort)
        run: pip install -r requirements.txt || true

      # Мини-проверка: модуль app.main импортируется — ок
      - name: Smoke import app.main
        shell: bash
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("app.main")
          print("SMOKE OK")
          PY
