name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (best effort)
        run: pip install -r requirements.txt || true
        - name: Install test deps
        run: pip install pytest
        - name: Run unit tests
        run: pytest -q
      - name: Smoke test
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("app")
          print("SMOKE OK")
          PY
