name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (best effort)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Install test deps
        run: pip install pytest

      - name: Run unit tests
        run: pytest -q

      - name: Smoke test (inline)
        run: |
          python - <<'PY'
          import importlib
          import sys
          # приложение должно импортироваться и экспортировать main()
          importlib.import_module("app")
          m = importlib.import_module("app.main")
          assert hasattr(m, "main"), "app.main must expose main()"
          print("SMOKE OK")
          PY
