name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (best effort)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      - name: Smoke import app.main
        shell: bash
        run: |
          set -Eeuo pipefail
          python - <<'PY'
          import sys, importlib
          try:
              m = importlib.import_module("app.main")
              assert hasattr(m, "main"), "app.main must define main()"
          except Exception as e:
              print("SMOKE FAILED:", repr(e), file=sys.stderr)
              raise
          else:
              print("SMOKE OK")
          PY

      - name: Run pytest if tests/ exists
        shell: bash
        run: |
          if [ -d tests ]; then
            python -m pip install pytest
            pytest -q
          else
            echo "No tests directory, skipping."
          fi
